name: Deploy to Azure and Explore GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: echo "Building docker image..."

      - name: Login ACR
        run: echo "Authenticate on ACR..."

      - name: Push Docker Image
        run: echo "Pushing Docker Image..."

      - name: "Login via Azure CLI"
        run: echo "Authenticate via Azure CLI..."

      - name: Deploy ACI
        run: | 
          echo "Creating container..."